"""add refresh token replacement tracking

Revision ID: 7920f7cf42f4
Revises: f60d200e9acf
Create Date: 2026-09-09 20:46:08.088515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7920f7cf42f4"
down_revision: str | Sequence[str] | None = "f60d200e9acf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("replaced_by_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        "refresh_tokens_replaced_by_id_fkey",
        "refresh_tokens",
        "refresh_tokens",
        ["replaced_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "refresh_tokens_replaced_by_id_fkey",
        "refresh_tokens",
        type_="foreignkey",
    )
    op.drop_column("refresh_tokens", "replaced_by_id")
    # ### end Alembic commands ###
