"""add session device fields

Revision ID: 9954927459ad
Revises: 835ed1e80be4
Create Date: 2026-09-08 21:44:31.028032

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9954927459ad"
down_revision: str | Sequence[str] | None = "835ed1e80be4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("browser", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "refresh_tokens", sa.Column("os", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "os")
    op.drop_column("refresh_tokens", "browser")
    # ### end Alembic commands ###
