"""add refresh token session fields

Revision ID: f60d200e9acf
Revises: 9954927459ad
Create Date: 2026-09-09 11:09:02.363520

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f60d200e9acf"
down_revision: str | Sequence[str] | None = "9954927459ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "family_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE refresh_tokens
        SET family_id = id
        WHERE family_id IS NULL
        """
    )

    op.alter_column(
        "refresh_tokens",
        "family_id",
        existing_type=sa.Uuid(),
        nullable=False,
    )

    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "family_id")
    # ### end Alembic commands ###
